// boards.js - Конфигурации микроконтроллеров

class BoardsManager {
    constructor() {
        this.boards = {};
        this.currentBoard = null;
    }

    async loadBoards() {
        try {
            const response = await fetch('data/boards.json');
            if (response.ok) {
                this.boards = await response.json();
                console.log('Платы загружены из JSON:', Object.keys(this.boards));
            } else {
                throw new Error('Файл не найден');
            }
        } catch (error) {
            console.warn('Загрузка boards.json не удалась, использую встроенные:', error.message);
            this.boards = this.getDefaultBoards();
        }
        return this.boards;
    }

    selectBoard(boardId) {
        this.currentBoard = this.boards[boardId] || null;
        return this.currentBoard;
    }

    getBoardsList() {
        return Object.entries(this.boards).map(([id, board]) => ({
            id: id,
            name: board.name,
            manufacturer: board.manufacturer,
            architecture: board.architecture,
            specs: board.specs
        }));
    }

    getPins(boardId = null) {
        const board = boardId ? this.boards[boardId] : this.currentBoard;
        return board ? board.pins : null;
    }

    getDigitalPins(boardId = null) {
        const pins = this.getPins(boardId);
        return pins ? pins.digital || [] : [];
    }

    getAnalogPins(boardId = null) {
        const pins = this.getPins(boardId);
        return pins ? pins.analog || [] : [];
    }

    getPWMPins(boardId = null) {
        const pins = this.getPins(boardId);
        return pins ? pins.pwm || [] : [];
    }

    generateHeader(boardId = null) {
        const board = boardId ? this.boards[boardId] : this.currentBoard;
        if (!board) {
            return '/*\n * Generated by Arduino Blocks Pro\n * Board: Not selected\n */';
        }
        
        return '/*\n' +
            ' * Generated by Arduino Blocks Pro\n' +
            ' * Board: ' + board.name + '\n' +
            ' * Architecture: ' + board.architecture + '\n' +
            ' * CPU: ' + board.specs.cpu + '\n' +
            ' * Clock: ' + board.specs.clock + '\n' +
            ' * Flash: ' + board.specs.flash + '\n' +
            ' * SRAM: ' + board.specs.sram + '\n' +
            ' */';
    }

    getDefaultBoards() {
        return {
            "arduino_uno": {
                "name": "Arduino Uno",
                "manufacturer": "Arduino",
                "architecture": "AVR",
                "specs": {
                    "cpu": "ATmega328P",
                    "clock": "16 MHz",
                    "flash": "32 KB",
                    "sram": "2 KB",
                    "eeprom": "1 KB"
                },
                "pins": {
                    "digital": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    "analog": ["A0", "A1", "A2", "A3", "A4", "A5"],
                    "pwm": [3, 5, 6, 9, 10, 11],
                    "special": {
                        "led_builtin": 13,
                        "tx": 1,
                        "rx": 0
                    }
                },
                "protocols": ["I2C", "SPI", "UART"],
                "i2c_pins": {"sda": "A4", "scl": "A5"},
                "default_includes": ["Arduino.h"]
            },
            "arduino_nano": {
                "name": "Arduino Nano",
                "manufacturer": "Arduino",
                "architecture": "AVR",
                "specs": {
                    "cpu": "ATmega328P",
                    "clock": "16 MHz",
                    "flash": "32 KB",
                    "sram": "2 KB"
                },
                "pins": {
                    "digital": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    "analog": ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7"],
                    "pwm": [3, 5, 6, 9, 10, 11]
                },
                "protocols": ["I2C", "SPI", "UART"],
                "default_includes": ["Arduino.h"]
            },
            "arduino_mega": {
                "name": "Arduino Mega 2560",
                "manufacturer": "Arduino",
                "architecture": "AVR",
                "specs": {
                    "cpu": "ATmega2560",
                    "clock": "16 MHz",
                    "flash": "256 KB",
                    "sram": "8 KB"
                },
                "pins": {
                    "digital": [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53],
                    "analog": ["A0","A1","A2","A3","A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14","A15"],
                    "pwm": [2,3,4,5,6,7,8,9,10,11,12,13,44,45,46]
                },
                "protocols": ["I2C", "SPI", "UART", "Serial1", "Serial2", "Serial3"],
                "default_includes": ["Arduino.h"]
            },
            "esp32_devkit": {
                "name": "ESP32 DevKit V1",
                "manufacturer": "Espressif",
                "architecture": "Xtensa",
                "specs": {
                    "cpu": "ESP32-D0WDQ6",
                    "clock": "240 MHz",
                    "flash": "4 MB",
                    "sram": "520 KB"
                },
                "pins": {
                    "digital": [0,2,4,5,12,13,14,15,16,17,18,19,21,22,23,25,26,27,32,33],
                    "analog": [32,33,34,35,36,39],
                    "pwm": [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,25,26,27,32,33]
                },
                "protocols": ["I2C", "SPI", "UART", "WiFi", "Bluetooth"],
                "default_includes": ["Arduino.h", "WiFi.h"]
            },
            "esp8266_nodemcu": {
                "name": "NodeMCU ESP8266",
                "manufacturer": "Espressif",
                "architecture": "Xtensa",
                "specs": {
                    "cpu": "ESP8266",
                    "clock": "80 MHz",
                    "flash": "4 MB",
                    "sram": "80 KB"
                },
                "pins": {
                    "digital": [0,1,2,3,4,5,12,13,14,15,16],
                    "analog": ["A0"],
                    "pwm": [0,1,2,3,4,5,12,13,14,15]
                },
                "protocols": ["I2C", "SPI", "UART", "WiFi"],
                "default_includes": ["Arduino.h", "ESP8266WiFi.h"]
            }
        };
    }
}

const boardsManager = new BoardsManager();