// boards.js - Конфигурации микроконтроллеров и работа с ними

class BoardsManager {
    constructor() {
        this.boards = {};
        this.currentBoard = null;
    }

    // Загрузка конфигураций плат
    async loadBoards() {
        try {
            const response = await fetch('data/boards.json');
            this.boards = await response.json();
            console.log('Платы загружены:', Object.keys(this.boards));
            return this.boards;
        } catch (error) {
            console.error('Ошибка загрузки плат:', error);
            // Загружаем встроенные конфигурации
            this.boards = this.getDefaultBoards();
            return this.boards;
        }
    }

    // Выбор платы
    selectBoard(boardId) {
        this.currentBoard = this.boards[boardId] || null;
        return this.currentBoard;
    }

    // Получение списка плат для UI
    getBoardsList() {
        return Object.entries(this.boards).map(([id, board]) => ({
            id: id,
            name: board.name,
            manufacturer: board.manufacturer,
            architecture: board.architecture
        }));
    }

    // Получение пинов платы
    getPins(boardId = null) {
        const board = boardId ? this.boards[boardId] : this.currentBoard;
        return board ? board.pins : null;
    }

    // Получение цифровых пинов
    getDigitalPins(boardId = null) {
        const pins = this.getPins(boardId);
        return pins ? pins.digital || [] : [];
    }

    // Получение аналоговых пинов
    getAnalogPins(boardId = null) {
        const pins = this.getPins(boardId);
        return pins ? pins.analog || [] : [];
    }

    // Получение PWM пинов
    getPWMPins(boardId = null) {
        const pins = this.getPins(boardId);
        return pins ? pins.pwm || [] : [];
    }

    // Получение поддерживаемых протоколов
    getProtocols(boardId = null) {
        const board = boardId ? this.boards[boardId] : this.currentBoard;
        return board ? board.protocols || [] : [];
    }

    // Генерация заголовка для кода Arduino
    generateHeader(boardId = null) {
        const board = boardId ? this.boards[boardId] : this.currentBoard;
        if (!board) return '';
        
        return `/*
 * Generated by Arduino Blocks
 * Board: ${board.name}
 * Architecture: ${board.architecture}
 * CPU: ${board.specs.cpu} @ ${board.specs.clock}
 * Flash: ${board.specs.flash}, SRAM: ${board.specs.sram}
 */

`;
    }

    // Встроенные конфигурации (заглушка, если JSON не загрузился)
    getDefaultBoards() {
        return {
            "arduino_uno": {
                "name": "Arduino Uno",
                "manufacturer": "Arduino",
                "architecture": "AVR",
                "specs": {
                    "cpu": "ATmega328P",
                    "clock": "16 MHz",
                    "flash": "32 KB",
                    "sram": "2 KB"
                },
                "pins": {
                    "digital": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    "analog": ["A0", "A1", "A2", "A3", "A4", "A5"],
                    "pwm": [3, 5, 6, 9, 10, 11],
                    "special": {
                        "led_builtin": 13,
                        "tx": 1,
                        "rx": 0
                    }
                },
                "protocols": ["I2C", "SPI", "UART"],
                "i2c_pins": {"sda": "A4", "scl": "A5"}
            },
            "arduino_mega": {
                "name": "Arduino Mega 2560",
                "manufacturer": "Arduino",
                "architecture": "AVR",
                "specs": {
                    "cpu": "ATmega2560",
                    "clock": "16 MHz",
                    "flash": "256 KB",
                    "sram": "8 KB"
                },
                "pins": {
                    "digital": Array.from({length: 54}, (_, i) => i),
                    "analog": Array.from({length: 16}, (_, i) => `A${i}`),
                    "pwm": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 44, 45, 46]
                },
                "protocols": ["I2C", "SPI", "UART", "Serial1", "Serial2", "Serial3"]
            },
            "esp32_devkit": {
                "name": "ESP32 DevKit V1",
                "manufacturer": "Espressif",
                "architecture": "Xtensa",
                "specs": {
                    "cpu": "ESP32-D0WDQ6",
                    "clock": "240 MHz",
                    "flash": "4 MB",
                    "sram": "520 KB"
                },
                "pins": {
                    "digital": [0, 2, 4, 5, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 32, 33],
                    "analog": [32, 33, 34, 35, 36, 39],
                    "pwm": Array.from({length: 16}, (_, i) => i),
                    "special": {
                        "led_builtin": 2
                    }
                },
                "protocols": ["I2C", "SPI", "UART", "WiFi", "Bluetooth"]
            }
        };
    }
}

// Экспорт глобального экземпляра
const boardsManager = new BoardsManager();